/** @type {import('@remix-run/dev').AppConfig} */
export default {
    ignoredRouteFiles: ["**/.*"],
    server: "./app/entry.worker.js",
    serverBuildPath: "build/index.js",
    serverModuleFormat: "esm",
    serverPlatform: "neutral",
    // appDirectory: "app",
    // assetsBuildDirectory: "public/build",
    // publicPath: "/build/",
    future: {
        v2_dev: true,
        v2_errorBoundary: true,
        v2_headers: true,
        v2_meta: true,
        v2_normalizeFormMethod: true,
        v2_routeConvention: true,
    },
    browserNodeBuiltinsPolyfill: {
        modules: {
            fs: true,
            buffer: true,
            stream: true,
            zlib: true,
            url: true,
            path: true,
        },
    },
    serverNodeBuiltinsPolyfill: {
        modules: {
            buffer: true,
            stream: true,
            zlib: true,
            url: true,
            path: true,
            crypto: true,
            events: true,
        },
    },
    serverDependenciesToBundle: [
        /^@shopify\/shopify-app-remix\/.*$/,
        "isbot",
        "@react-pdf/renderer",
        "@react-pdf/layout",
        "@react-pdf/pdfkit",
        "@react-pdf/font",
        "@react-pdf/image",
        "@react-pdf/stylesheet",
        "@react-pdf/primitives",
        "@react-pdf/textkit",
        "@react-pdf/fns",
        "yoga-layout",
    ],
};
